// app/layout.jsx
import "./globals.css";
import StoryBlokProvider from "@/components/StoryBlokProvider";
import { getStoryblokApi } from "@/lib/storyblok";
import Header from "@/components/sb/Header";
import Footer from "@/components/sb/Footer";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
  style: ["normal", "italic"], // om du vill kunna använda italic
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const storyblok = getStoryblokApi();
  const global = await storyblok.get("cdn/stories/global", { version: "draft" });

  return (
    <html lang="sv">
      <body className={`${inter.variable} font-sans antialiased`}>
        <StoryBlokProvider>
          <Header blok={global.data.story.content.header[0]} />
          {children}
          <Footer blok={global.data.story.content.footer[0]} />
        </StoryBlokProvider>
      </body>
    </html>
  );
}
